name: Release Cap2SPM

on:
    push:
        tags:
            '*.*.*'

jobs:
    release:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4
            - uses: swift-actions/setup-swift@v1
              with:
                swift-version: "6.1"
            - name: Build for Release
              run: swift build -c release --arch arm64 --arch x86_64 --product cap2spm
            - name: Zip Executable
              run: zip -j cap2spm.zip .build/apple/Products/Release/cap2spm
            - name: Create Release
              uses: softprops/action-gh-release@v1
              with:
                files: cap2spm.zip
                token: ${{ secrets.GITHUB_TOKEN }}
